trigger:
  branches:
    include:
      - refs/tags/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  python.version: 3.7.6

steps:

- bash: |
    VERSION_TAG=`git describe --abbrev=0 --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
    echo $VERSION_TAG
  displayName: Set VERSION_TAG
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pipenv
  displayName: 'Install Python Dependencies'

- bash: |
    mkdir .venv
    pipenv install
    pipenv graph
  displayName: 'Install Package Dependencies'

- script: |
    sudo apt-get install ruby ruby-dev rubygems build-essential
    sudo gem install --no-document fpm 
    fpm --version
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'Install FBS Dependencies'

- task: PythonScript@0
  inputs:
    script: |
      '''Temp fix for PyInstaller==3.6 acc. to https://github.com/mherrmann/fbs/issues/169'''
      
      from os import path, rename
      
      org_file = path.normpath('.venv/lib/python3.7/site-packages/fbs/freeze/hooks/hook-PySide2.py')
      rename_file = path.normpath('.venv/lib/python3.7/site-packages/fbs/freeze/hooks/hook-PySide2_fbs.py')

      rename(org_file, rename_file)

      print(f'Renamed ${org_file} to ${rename_file}.')
  displayName: 'Fix FBS-PyInstaller Issue'

- script: |
    pipenv run fbs freeze
  displayName: 'Build App'

- script: |
    pipenv run fbs installer
  displayName: 'Make Installer'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'target/vMono/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/vMono-windows-portable.zip'
    replaceExistingArchive: true
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Make Windows Portable App'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'target/'
    Contents: |
      *.deb
      *.dmg
      *Setup.exe
      *-windows-portable.zip
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Assets to Artifact Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(System.JobName)'
  displayName: 'Publish Assets in Artifact Directory'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_vipranarayan14'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: '$(VERSION_TAG)'
    title: '$(VERSION_TAG)'
    assetUploadMode: 'replace'
    isDraft: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  displayName: 'Create GitHub Releases with Assets'
