name: Build App

on: push

jobs:
  build:
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include: 
          - os: windows-latest
            artifact_name: vMonoSetup.exe
            asset_name: vmono-windows-amd64
          - os: ubuntu-latest
            artifact_name: vMono.deb
            asset_name: vmono-linux-amd64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
        
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
  
    - name: Install FBS requirements
      run: |
        sudo apt-get update
        sudo apt-get install ruby ruby-dev rubygems build-essential

        sudo gem install --no-document fpm

        fpm --version

      if: matrix.os == 'ubuntu-latest'
        
    - name: Install Package dependencies
      run: |
        pipenv install
        pipenv graph
    
    - name: Build app
      run: |
        pipenv run fbs freeze

    - name: Make installer
      run: |
        pipenv run fbs installer
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: target/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/zip

      
