name: Build App

on: push

jobs:
  build:
    
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
        
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
      
    - name: Install Windows requirements
      run: |
        pipenv install pypiwin32
        pipenv install pywin32-ctypes
      if: matrix.platform == 'windows-latest'
  
    - name: Install Linux requirements
      run: |
        sudo apt-get update
        sudo apt-get install ruby ruby-dev rubygems build-essential

        sudo gem install --no-document fpm

        fpm --version

      if: matrix.platform == 'ubuntu-latest'
        
    - name: Install Package dependencies
      run: |
        pipenv install
        pipenv graph
    
    - name: Build app
      run: |
        pipenv run fbs freeze

    - name: Make installer
      run: |
        pipenv run fbs installer

      
